### ISSUE TITLE
t/04_client_tests.t fails with perl 5.21.7

### ISSUE THREAD

**Issue by eserte** [Weborama/Riak-Light#18]
See http://matrix.cpantesters.org/?dist=Riak-Light for a pass/fail overview and http://www.cpantesters.org/cpan/report/d64550d2-8a73-11e4-8b82-bb06e1bfc7aa for a sample fail report. I don't see a simple reason why it's failing. If you think this is a perl regression, then please report at perl5-porters.

**Comment by peczenyj** [comment]
Seems it was fixed https://rt.perl.org/Public/Bug/Display.html?id=123503
